Ticket2707 add ioc samsm300
ISISComputingGroup/EPICS-motor pull request #19
Opened 2018-01-17 13:37 UTC by John-Holt-Tessella

Add SM300 drivers

2018-01-22 13:19 UTC, FreddieAkeroyd commented on motorApp/SM300Src/SM300Driver.h
> +#define NUM_SM300_PARAMS 4
The ususal asyn way is not to hard code the number of parameters, but to define the first and last parameter names and then use "last - first + 1" so new parameters can be added without needing to (or forgetting to) update the number. In  asyn 4.32 the "paramTableSize" argument is deprecated, but i expect this has not made it into asynMotorController yet

2018-01-23 09:25 UTC, AdrianPotter requested changes
Couple of things to think about. Nothing major. Freddie's is probably the biggest point.

2018-01-23 09:25 UTC, AdrianPotter commented on motorApp/SM300Src/SM300Driver.cpp
> +#define NINT(f) (int)((f)>0 ? (f)+0.5 : (f)-0.5)
This doesn't appear to be used

2018-01-23 09:25 UTC, AdrianPotter commented on motorApp/SM300Src/SM300Driver.cpp
> +  * Querry string is prefeced with ACK STX and postfixed with EOT
Spelling: `Querry`. Please fix this and subsequent

2018-01-23 09:25 UTC, AdrianPotter commented on motorApp/SM300Src/SM300Driver.cpp
> +	if (sendCommand("PEL1")) return status;
Is there a reason for not doing this as a loop? Much easier if you ever want to change what to do for each command.

```
const char * commands[] = {
    "PEL1",
    "B/ G01",
    ...
};
int n_array = (sizeof (commands) / sizeof (const char *));
for (i = 0; i < n_array; i++) {
    if (sendCommand(commands[i]) return status;
}
```

2018-01-29 17:20 UTC, AdrianPotter approved these changes

2018-01-29 17:21 UTC, merged