Add home mode 4 to mclennan
ISISComputingGroup/EPICS-motor pull request #38
Opened 2021-03-08 11:52 UTC by Tom-Willemsen

https://github.com/ISISComputingGroup/IBEX/issues/5729

2021-03-12 09:52 UTC, John-Holt-Tessella requested changes, later dismissed
Update documentation including home modes in https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/McLennan-motors

2021-03-12 09:52 UTC, John-Holt-Tessella commented on motorApp/MclennanSrc/devPM304.cc
>          if ( home_mode==motor_default || home_mode==reverse_and_zero ) {
```suggestion
        if ( home_mode==motor_default || home_mode==reverse_and_zero || home_mode==forward_and_zero) {
```

2021-03-12 09:52 UTC, John-Holt-Tessella commented on motorApp/MclennanSrc/devPM304.cc
> +        int motor_default=0, constant_velocity=1, reverse_and_zero=2, constant_velocity_move_and_zero=3, forward_and_zero=4;
Can we use the defines from the homing st? or repeat them in this file rather than this?

2021-03-27 13:13 UTC, DominicOram approved these changes
Looks good, thanks

2021-03-27 13:55 UTC, merged